apiVersion: v1
kind: Secret
metadata:
  name: minio-creds-secret
  namespace: myservice-minio
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER="admin"
    export MINIO_ROOT_PASSWORD="12345678"
    export MINIO_BROWSER="on"
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-creds-secret
  namespace: myservice
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER="admin"
    export MINIO_ROOT_PASSWORD="12345678"
    export MINIO_BROWSER="on"